import {
  Anchor,
  BookOpen,
  Calendar,
  Castle,
  Church,
  Crown,
  FileText,
  Flag,
  Gem,
  Ghost,
  Landmark,
  MapPin,
  Mountain,
  Scroll,
  Shield,
  Ship,
  Skull,
  Sparkles,
  Sun,
  Swords,
  Trees,
  User,
  Users,
  type LucideIcon,
} from 'lucide-react';

/** Icons a kind of note can have, by name (stored with the kind). */
export const ICONS: Record<string, LucideIcon | undefined> = {
  file: FileText,
  user: User,
  users: Users,
  'map-pin': MapPin,
  flag: Flag,
  calendar: Calendar,
  scroll: Scroll,
  church: Church,
  sun: Sun,
  anchor: Anchor,
  ship: Ship,
  castle: Castle,
  landmark: Landmark,
  crown: Crown,
  swords: Swords,
  shield: Shield,
  gem: Gem,
  skull: Skull,
  ghost: Ghost,
  mountain: Mountain,
  trees: Trees,
  sparkles: Sparkles,
  book: BookOpen,
};

export const ICON_NAMES = Object.keys(ICONS);
