/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CompendiumRouteImport } from './routes/compendium'
import { Route as EncountersRouteImport } from './routes/encounters'
import { Route as HomebrewRouteImport } from './routes/homebrew'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CampaignsIdRouteImport } from './routes/campaigns_.$id'
import { Route as CardsIdRouteImport } from './routes/cards_.$id'
import { Route as CharactersIdRouteImport } from './routes/characters_.$id'
import { Route as CompendiumKeyRouteImport } from './routes/compendium_.$key'
import { Route as HomebrewPackRouteImport } from './routes/homebrew_.$pack'
import { Route as SettingsDataRouteImport } from './routes/settings_.data'
import { Route as SettingsSyncRouteImport } from './routes/settings_.sync'
import { Route as CharactersIdPrintRouteImport } from './routes/characters_.$id_.print'
import { Route as CompendiumAdventureIdRouteImport } from './routes/compendium_.adventure.$id'
import { Route as CompendiumBookIdRouteImport } from './routes/compendium_.book.$id'
import { Route as CompendiumLibraryKindRouteImport } from './routes/compendium_.library.$kind'
import { Route as CompendiumListCategoryRouteImport } from './routes/compendium_.list.$category'
import { Route as CompendiumQuickrefIdRouteImport } from './routes/compendium_.quickref.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumRoute = CompendiumRouteImport.update({
  id: '/compendium',
  path: '/compendium',
  getParentRoute: () => rootRouteImport,
} as any)
const EncountersRoute = EncountersRouteImport.update({
  id: '/encounters',
  path: '/encounters',
  getParentRoute: () => rootRouteImport,
} as any)
const HomebrewRoute = HomebrewRouteImport.update({
  id: '/homebrew',
  path: '/homebrew',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns_/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIdRoute = CardsIdRouteImport.update({
  id: '/cards_/$id',
  path: '/cards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters_/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumKeyRoute = CompendiumKeyRouteImport.update({
  id: '/compendium_/$key',
  path: '/compendium/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const HomebrewPackRoute = HomebrewPackRouteImport.update({
  id: '/homebrew_/$pack',
  path: '/homebrew/$pack',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/settings_/data',
  path: '/settings/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/settings_/sync',
  path: '/settings/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdPrintRoute = CharactersIdPrintRouteImport.update({
  id: '/characters_/$id_/print',
  path: '/characters/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumAdventureIdRoute = CompendiumAdventureIdRouteImport.update({
  id: '/compendium_/adventure/$id',
  path: '/compendium/adventure/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumBookIdRoute = CompendiumBookIdRouteImport.update({
  id: '/compendium_/book/$id',
  path: '/compendium/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumLibraryKindRoute = CompendiumLibraryKindRouteImport.update({
  id: '/compendium_/library/$kind',
  path: '/compendium/library/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumListCategoryRoute = CompendiumListCategoryRouteImport.update({
  id: '/compendium_/list/$category',
  path: '/compendium/list/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumQuickrefIdRoute = CompendiumQuickrefIdRouteImport.update({
  id: '/compendium_/quickref/$id',
  path: '/compendium/quickref/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/campaigns': typeof CampaignsRoute
  '/cards': typeof CardsRoute
  '/characters': typeof CharactersRoute
  '/compendium': typeof CompendiumRoute
  '/encounters': typeof EncountersRoute
  '/homebrew': typeof HomebrewRoute
  '/journal': typeof JournalRoute
  '/maps': typeof MapsRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cards/$id': typeof CardsIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/compendium/$key': typeof CompendiumKeyRoute
  '/homebrew/$pack': typeof HomebrewPackRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/characters/$id/print': typeof CharactersIdPrintRoute
  '/compendium/adventure/$id': typeof CompendiumAdventureIdRoute
  '/compendium/book/$id': typeof CompendiumBookIdRoute
  '/compendium/library/$kind': typeof CompendiumLibraryKindRoute
  '/compendium/list/$category': typeof CompendiumListCategoryRoute
  '/compendium/quickref/$id': typeof CompendiumQuickrefIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/campaigns': typeof CampaignsRoute
  '/cards': typeof CardsRoute
  '/characters': typeof CharactersRoute
  '/compendium': typeof CompendiumRoute
  '/encounters': typeof EncountersRoute
  '/homebrew': typeof HomebrewRoute
  '/journal': typeof JournalRoute
  '/maps': typeof MapsRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cards/$id': typeof CardsIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/compendium/$key': typeof CompendiumKeyRoute
  '/homebrew/$pack': typeof HomebrewPackRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/characters/$id/print': typeof CharactersIdPrintRoute
  '/compendium/adventure/$id': typeof CompendiumAdventureIdRoute
  '/compendium/book/$id': typeof CompendiumBookIdRoute
  '/compendium/library/$kind': typeof CompendiumLibraryKindRoute
  '/compendium/list/$category': typeof CompendiumListCategoryRoute
  '/compendium/quickref/$id': typeof CompendiumQuickrefIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/campaigns': typeof CampaignsRoute
  '/cards': typeof CardsRoute
  '/characters': typeof CharactersRoute
  '/compendium': typeof CompendiumRoute
  '/encounters': typeof EncountersRoute
  '/homebrew': typeof HomebrewRoute
  '/journal': typeof JournalRoute
  '/maps': typeof MapsRoute
  '/settings': typeof SettingsRoute
  '/campaigns_/$id': typeof CampaignsIdRoute
  '/cards_/$id': typeof CardsIdRoute
  '/characters_/$id': typeof CharactersIdRoute
  '/compendium_/$key': typeof CompendiumKeyRoute
  '/homebrew_/$pack': typeof HomebrewPackRoute
  '/settings_/data': typeof SettingsDataRoute
  '/settings_/sync': typeof SettingsSyncRoute
  '/characters_/$id_/print': typeof CharactersIdPrintRoute
  '/compendium_/adventure/$id': typeof CompendiumAdventureIdRoute
  '/compendium_/book/$id': typeof CompendiumBookIdRoute
  '/compendium_/library/$kind': typeof CompendiumLibraryKindRoute
  '/compendium_/list/$category': typeof CompendiumListCategoryRoute
  '/compendium_/quickref/$id': typeof CompendiumQuickrefIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/campaigns'
    | '/cards'
    | '/characters'
    | '/compendium'
    | '/encounters'
    | '/homebrew'
    | '/journal'
    | '/maps'
    | '/settings'
    | '/campaigns/$id'
    | '/cards/$id'
    | '/characters/$id'
    | '/compendium/$key'
    | '/homebrew/$pack'
    | '/settings/data'
    | '/settings/sync'
    | '/characters/$id/print'
    | '/compendium/adventure/$id'
    | '/compendium/book/$id'
    | '/compendium/library/$kind'
    | '/compendium/list/$category'
    | '/compendium/quickref/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/campaigns'
    | '/cards'
    | '/characters'
    | '/compendium'
    | '/encounters'
    | '/homebrew'
    | '/journal'
    | '/maps'
    | '/settings'
    | '/campaigns/$id'
    | '/cards/$id'
    | '/characters/$id'
    | '/compendium/$key'
    | '/homebrew/$pack'
    | '/settings/data'
    | '/settings/sync'
    | '/characters/$id/print'
    | '/compendium/adventure/$id'
    | '/compendium/book/$id'
    | '/compendium/library/$kind'
    | '/compendium/list/$category'
    | '/compendium/quickref/$id'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/campaigns'
    | '/cards'
    | '/characters'
    | '/compendium'
    | '/encounters'
    | '/homebrew'
    | '/journal'
    | '/maps'
    | '/settings'
    | '/campaigns_/$id'
    | '/cards_/$id'
    | '/characters_/$id'
    | '/compendium_/$key'
    | '/homebrew_/$pack'
    | '/settings_/data'
    | '/settings_/sync'
    | '/characters_/$id_/print'
    | '/compendium_/adventure/$id'
    | '/compendium_/book/$id'
    | '/compendium_/library/$kind'
    | '/compendium_/list/$category'
    | '/compendium_/quickref/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  CampaignsRoute: typeof CampaignsRoute
  CardsRoute: typeof CardsRoute
  CharactersRoute: typeof CharactersRoute
  CompendiumRoute: typeof CompendiumRoute
  EncountersRoute: typeof EncountersRoute
  HomebrewRoute: typeof HomebrewRoute
  JournalRoute: typeof JournalRoute
  MapsRoute: typeof MapsRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CardsIdRoute: typeof CardsIdRoute
  CharactersIdRoute: typeof CharactersIdRoute
  CompendiumKeyRoute: typeof CompendiumKeyRoute
  HomebrewPackRoute: typeof HomebrewPackRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  CharactersIdPrintRoute: typeof CharactersIdPrintRoute
  CompendiumAdventureIdRoute: typeof CompendiumAdventureIdRoute
  CompendiumBookIdRoute: typeof CompendiumBookIdRoute
  CompendiumLibraryKindRoute: typeof CompendiumLibraryKindRoute
  CompendiumListCategoryRoute: typeof CompendiumListCategoryRoute
  CompendiumQuickrefIdRoute: typeof CompendiumQuickrefIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium': {
      id: '/compendium'
      path: '/compendium'
      fullPath: '/compendium'
      preLoaderRoute: typeof CompendiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounters': {
      id: '/encounters'
      path: '/encounters'
      fullPath: '/encounters'
      preLoaderRoute: typeof EncountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homebrew': {
      id: '/homebrew'
      path: '/homebrew'
      fullPath: '/homebrew'
      preLoaderRoute: typeof HomebrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns_/$id': {
      id: '/campaigns_/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards_/$id': {
      id: '/cards_/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters_/$id': {
      id: '/characters_/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium_/$key': {
      id: '/compendium_/$key'
      path: '/compendium/$key'
      fullPath: '/compendium/$key'
      preLoaderRoute: typeof CompendiumKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homebrew_/$pack': {
      id: '/homebrew_/$pack'
      path: '/homebrew/$pack'
      fullPath: '/homebrew/$pack'
      preLoaderRoute: typeof HomebrewPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/data': {
      id: '/settings_/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/sync': {
      id: '/settings_/sync'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters_/$id_/print': {
      id: '/characters_/$id_/print'
      path: '/characters/$id/print'
      fullPath: '/characters/$id/print'
      preLoaderRoute: typeof CharactersIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium_/adventure/$id': {
      id: '/compendium_/adventure/$id'
      path: '/compendium/adventure/$id'
      fullPath: '/compendium/adventure/$id'
      preLoaderRoute: typeof CompendiumAdventureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium_/book/$id': {
      id: '/compendium_/book/$id'
      path: '/compendium/book/$id'
      fullPath: '/compendium/book/$id'
      preLoaderRoute: typeof CompendiumBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium_/library/$kind': {
      id: '/compendium_/library/$kind'
      path: '/compendium/library/$kind'
      fullPath: '/compendium/library/$kind'
      preLoaderRoute: typeof CompendiumLibraryKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium_/list/$category': {
      id: '/compendium_/list/$category'
      path: '/compendium/list/$category'
      fullPath: '/compendium/list/$category'
      preLoaderRoute: typeof CompendiumListCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium_/quickref/$id': {
      id: '/compendium_/quickref/$id'
      path: '/compendium/quickref/$id'
      fullPath: '/compendium/quickref/$id'
      preLoaderRoute: typeof CompendiumQuickrefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  CampaignsRoute: CampaignsRoute,
  CardsRoute: CardsRoute,
  CharactersRoute: CharactersRoute,
  CompendiumRoute: CompendiumRoute,
  EncountersRoute: EncountersRoute,
  HomebrewRoute: HomebrewRoute,
  JournalRoute: JournalRoute,
  MapsRoute: MapsRoute,
  SettingsRoute: SettingsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CardsIdRoute: CardsIdRoute,
  CharactersIdRoute: CharactersIdRoute,
  CompendiumKeyRoute: CompendiumKeyRoute,
  HomebrewPackRoute: HomebrewPackRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  CharactersIdPrintRoute: CharactersIdPrintRoute,
  CompendiumAdventureIdRoute: CompendiumAdventureIdRoute,
  CompendiumBookIdRoute: CompendiumBookIdRoute,
  CompendiumLibraryKindRoute: CompendiumLibraryKindRoute,
  CompendiumListCategoryRoute: CompendiumListCategoryRoute,
  CompendiumQuickrefIdRoute: CompendiumQuickrefIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
