/**
 * Names for NPCs and the name generator: a naming style per kind of species (syllables to start,
 * maybe a middle, an ending by gender, sometimes a family name or a clan/epithet). Any species
 * of the character builder maps to a style by its name (High Elf → elvish, Aven → avian…). The
 * syllables are the app's own, so generated names are the DM's to keep.
 */

export type Rng = () => number;

export const pick = <T>(list: readonly T[], rng: Rng): T =>
  list[Math.floor(rng() * list.length)] as T;

interface Style {
  start: readonly string[];
  middle: readonly string[];
  /** Endings for men, for women; people of other genders take either. */
  end: readonly [readonly string[], readonly string[]];
  /** Family names, clans or epithets, after the given name. */
  family?: readonly string[];
  /** How often a family name is added (0–1); always when absent. */
  familyChance?: number;
  /** Joins given and family name (" " by default; " of the " for clans…). */
  join?: string;
}

const STYLES = {
  human: {
    start: [
      'Al',
      'Bran',
      'Cal',
      'Dar',
      'Ed',
      'Gar',
      'Hal',
      'Jor',
      'Mar',
      'Ros',
      'Sel',
      'Tam',
      'Wil',
      'Ad',
      'Ber',
      'Cor',
      'Ev',
      'Fen',
      'Lor',
      'Nor',
      'Os',
      'Ral',
      'Ste',
      'Ul',
      'Ver',
      'Ash',
      'Bel',
      'Del',
      'Har',
      'Ka',
    ],
    middle: ['', '', '', 'a', 'e', 'i', 'o', 'ar', 'en'],
    end: [
      [
        'ric',
        'den',
        'win',
        'mund',
        'ton',
        'as',
        'an',
        'ard',
        'bert',
        'ford',
        'lin',
        'mar',
        'ric',
        'ven',
        'ward',
      ],
      [
        'a',
        'ine',
        'ella',
        'wyn',
        'is',
        'ey',
        'ara',
        'ette',
        'ia',
        'issa',
        'ora',
        'een',
        'elle',
        'anne',
        'ith',
      ],
    ],
    family: [
      'Ashford',
      'Blackwood',
      'Carrow',
      'Dunmore',
      'Fairweather',
      'Hale',
      'Marsh',
      'Thorne',
      'Brightwater',
      'Coldridge',
      'Dawson',
      'Everly',
      'Graves',
      'Holloway',
      'Kettle',
      'Larkin',
      'Merrow',
      'Pike',
      'Quill',
      'Redfern',
      'Saltmarsh',
      'Tanner',
      'Vance',
      'Wren',
      'Yardley',
      'Cooper',
      'Fletcher',
      'Mason',
      'Rook',
      'Sterling',
    ],
    familyChance: 0.85,
  },
  elf: {
    start: [
      'Ae',
      'Cael',
      'El',
      'Fae',
      'Gal',
      'Ith',
      'Lae',
      'Mir',
      'Syl',
      'Thal',
      'Vae',
      'Ara',
      'Bel',
      'Cor',
      'Ely',
      'Ili',
      'Lia',
      'Nae',
      'Qil',
      'Rha',
      'Shae',
      'Tae',
      'Yl',
      'Zan',
    ],
    middle: ['', 'a', 'e', 'i', 'la', 'ri', 'th', 'ndi', 'va'],
    end: [
      [
        'ndor',
        'rian',
        'thas',
        'vir',
        'lis',
        'ion',
        'aril',
        'endil',
        'ithor',
        'olas',
        'uin',
        'varis',
      ],
      ['wyn', 'riel', 'thia', 'lara', 'ndra', 'ael', 'ielle', 'issa', 'naë', 'ora', 'sira', 'yth'],
    ],
    family: [
      'Amakiir',
      'Galanodel',
      'Liadon',
      'Meliamne',
      'Siannodel',
      'Xiloscient',
      'Brightleaf',
      'Moonwhisper',
      'Nightbreeze',
      'Starfall',
      'Silverfrond',
      'Dawnpetal',
      'Ilphelkiir',
      'Holimion',
    ],
    familyChance: 0.8,
  },
  dwarf: {
    start: [
      'Bar',
      'Dol',
      'Dur',
      'Gim',
      'Har',
      'Kil',
      'Mor',
      'Orn',
      'Thor',
      'Brom',
      'Bal',
      'Dag',
      'Eb',
      'Fal',
      'Grun',
      'Ru',
      'Tor',
      'Vond',
      'Ad',
      'Hlin',
    ],
    middle: ['', '', 'a', 'i', 'u', 'ri', 'go'],
    end: [
      ['ak', 'in', 'rik', 'grim', 'dain', 'bek', 'dur', 'gar', 'nar', 'rak', 'thur', 'olf'],
      ['dis', 'hild', 'ra', 'unn', 'wyn', 'dra', 'gret', 'ida', 'lin', 'run', 'tra', 'vi'],
    ],
    family: [
      'Battlehammer',
      'Fireforge',
      'Gorunn',
      'Holderhek',
      'Ironfist',
      'Stonebeard',
      'Anvilborn',
      'Bronzebelly',
      'Deepdelver',
      'Flintheart',
      'Goldvein',
      'Ironbraid',
      'Rumnaheim',
      'Torunn',
      'Ungart',
      'Coppercask',
    ],
  },
  halfling: {
    start: [
      'Bel',
      'Cor',
      'Fin',
      'Mer',
      'Per',
      'Pip',
      'Ros',
      'Wel',
      'Lid',
      'Mil',
      'And',
      'Cad',
      'Eld',
      'Gar',
      'Lyle',
      'Nor',
      'Os',
      'Rose',
      'Tob',
      'Ver',
    ],
    middle: ['', '', 'a', 'i', 'o', 'ri'],
    end: [
      ['ric', 'do', 'nan', 'by', 'ton', 'bo', 'den', 'ger', 'lo', 'mac', 'wise', 'kin'],
      ['ie', 'la', 'ly', 'ri', 'sy', 'belle', 'da', 'lee', 'na', 'pea', 'sie', 'wyn'],
    ],
    family: [
      'Brushgather',
      'Goodbarrel',
      'Greenbottle',
      'Tealeaf',
      'Thorngage',
      'Underbough',
      'Hilltopple',
      'Honeypot',
      'Leagallow',
      'Quickstep',
      'Tallfellow',
      'Warmwater',
      'Applebrook',
      'Bramblefoot',
    ],
  },
  gnome: {
    start: [
      'Al',
      'Bim',
      'Dim',
      'Fon',
      'Gim',
      'Nim',
      'Orr',
      'Sin',
      'Wren',
      'Zook',
      'Boddy',
      'Carl',
      'Ella',
      'Fen',
      'Jeb',
      'Kel',
      'Loo',
      'Nack',
      'Quill',
      'Tink',
    ],
    middle: ['', 'ble', 'li', 'ni', 'po', 'wi', 'zz'],
    end: [
      ['ble', 'bin', 'kin', 'nock', 'ston', 'bo', 'dle', 'fizz', 'nik', 'wick'],
      ['bi', 'ella', 'na', 'wick', 'ra', 'bell', 'dee', 'lin', 'sy', 'tilly'],
    ],
    family: [
      'Beren',
      'Daergel',
      'Folkor',
      'Garrick',
      'Nackle',
      'Timbers',
      'Turen',
      'Cogsworth',
      'Fizzlebang',
      'Gearspark',
      'Sprocket',
      'Whistlebottom',
    ],
  },
  orc: {
    start: [
      'Dench',
      'Gor',
      'Hol',
      'Kru',
      'Mog',
      'Rag',
      'Shum',
      'Thok',
      'Ug',
      'Yev',
      'Arg',
      'Bru',
      'Dur',
      'Grak',
      'Kar',
      'Nag',
      'Ruk',
      'Vol',
      'Zug',
      'Ov',
    ],
    middle: ['', '', 'a', 'o', 'u', 'ra'],
    end: [
      ['ash', 'ar', 'gar', 'mak', 'tusk', 'dak', 'gul', 'nash', 'rok', 'zar'],
      ['ga', 'ka', 'ra', 'sha', 'ul', 'gra', 'na', 'reka', 'tha', 'va'],
    ],
    family: [
      'Bloodfang',
      'Ironjaw',
      'Skullsplitter',
      'Stonetusk',
      'Gorefist',
      'Ashborn',
      'Redhand',
      'Wolfbane',
    ],
    familyChance: 0.5,
  },
  tiefling: {
    start: [
      'Ak',
      'Bar',
      'Dam',
      'Kal',
      'Lev',
      'Mor',
      'Nem',
      'Ori',
      'Ska',
      'Zar',
      'Am',
      'Bry',
      'Cri',
      'Ek',
      'Ia',
      'Mak',
      'Ny',
      'Pel',
      'Ri',
      'Vel',
    ],
    middle: ['', 'a', 'e', 'i', 'ka', 'th', 'ze'],
    end: [
      ['akos', 'thos', 'mon', 'ius', 'zar', 'ael', 'eth', 'mos', 'rax', 'vos'],
      ['kis', 'ria', 'theia', 'lith', 'ka', 'nyx', 'ora', 'rissa', 'vex', 'zara'],
    ],
    // Virtue names some tieflings take.
    family: [
      'Hope',
      'Sorrow',
      'Ember',
      'Ash',
      'Torment',
      'Glory',
      'Quiet',
      'Reverie',
      'Mercy',
      'Carrion',
    ],
    familyChance: 0.35,
    join: ' "',
  },
  dragonborn: {
    start: [
      'Ar',
      'Bala',
      'Don',
      'Gha',
      'Kri',
      'Med',
      'Nad',
      'Pand',
      'Sora',
      'Tor',
      'Ali',
      'Bhar',
      'Dra',
      'Har',
      'Kava',
      'Mish',
      'Rho',
      'Sul',
      'Thava',
      'Vrak',
    ],
    middle: ['', 'a', 'i', 'ja', 'ra', 'sh'],
    end: [
      ['ash', 'dar', 'jhan', 'nar', 'rinn', 'ghor', 'kan', 'rax', 'thos', 'zoth'],
      ['ra', 'shann', 'thra', 'vys', 'zil', 'sha', 'nyx', 'rith', 'tha', 'ylla'],
    ],
    family: [
      'Clethtinthiallor',
      'Daardendrian',
      'Delmirev',
      'Drachedandion',
      'Kepeshkmolik',
      'Kimbatuul',
      'Myastan',
      'Nemmonis',
      'Norixius',
      'Yarjerit',
    ],
  },
  giant: {
    start: [
      'Aug',
      'Eg',
      'Gae',
      'Kav',
      'Lo',
      'Mau',
      'Pa',
      'Tha',
      'Vim',
      'Bor',
      'Kel',
      'Ny',
      'Ola',
      'Tor',
    ],
    middle: ['', 'a', 'ae', 'i', 'o'],
    end: [
      ['ak', 'gath', 'lak', 'rok', 'thak', 'ume', 'vak'],
      ['ga', 'ia', 'lei', 'na', 'thi', 'ven', 'ya'],
    ],
    family: [
      'Bearkiller',
      'Dawncaller',
      'Fearless',
      'Flintfinder',
      'Hornsplitter',
      'Keeneye',
      'Lonehunter',
      'Longleaper',
      'Rootsmasher',
      'Skywatcher',
      'Steadyhand',
      'Threadtwister',
    ],
  },
  goblin: {
    start: [
      'Bik',
      'Drub',
      'Fiz',
      'Grik',
      'Krag',
      'Mug',
      'Nix',
      'Pog',
      'Ruk',
      'Snag',
      'Vik',
      'Zib',
      'Gob',
      'Lurk',
      'Skeev',
    ],
    middle: ['', '', 'a', 'i', 'le'],
    end: [
      ['git', 'gob', 'ik', 'nak', 'snik', 'ub', 'zek'],
      ['a', 'ba', 'ka', 'na', 'ri', 'ska', 'zi'],
    ],
    family: ['the Quick', 'the Sly', 'Ratbiter', 'Shinkicker', 'Mudfoot', 'Rustnail', 'Sootnose'],
    familyChance: 0.5,
  },
  celestial: {
    start: ['Ar', 'Cel', 'Era', 'Gab', 'Hal', 'Isa', 'Lum', 'Mal', 'Ori', 'Sar', 'Ura', 'Zar'],
    middle: ['', 'a', 'e', 'i', 'iel', 'ra'],
    end: [
      ['iel', 'ael', 'on', 'us', 'ias', 'em'],
      ['iel', 'ara', 'ina', 'ia', 'eth', 'ys'],
    ],
    family: [
      'Dawnward',
      'Lightbringer',
      'Sunvale',
      'Brightwing',
      'Haloran',
      'Starling',
      'Goldmantle',
    ],
    familyChance: 0.6,
  },
  elemental: {
    start: [
      'Ash',
      'Bre',
      'Cin',
      'Dra',
      'Ema',
      'Fla',
      'Gale',
      'Ky',
      'Mar',
      'Pyr',
      'Sto',
      'Tid',
      'Ven',
      'Zeph',
    ],
    middle: ['', 'a', 'e', 'i', 'o'],
    end: [
      ['an', 'ar', 'eth', 'is', 'or', 'ron', 'yx'],
      ['a', 'ae', 'ia', 'ra', 'sa', 'wyn', 'ys'],
    ],
    family: [
      'of the Ember Tide',
      'Stormborn',
      'Deepcurrent',
      'Ashwalker',
      'Windcaller',
      'Stoneblood',
      'Flameheart',
    ],
    familyChance: 0.5,
  },
  feline: {
    start: [
      'Cloud',
      'Five',
      'Jade',
      'Night',
      'Rain',
      'Smoke',
      'Sun',
      'Two',
      'Wind',
      'Copper',
      'Silent',
      'Quick',
      'Bright',
      'Ember',
    ],
    middle: [' on the ', ' of the ', ' Under ', ' Before '],
    end: [
      ['Mountain', 'River', 'Moon', 'Hunt', 'Dawn', 'Storm'],
      ['Meadow', 'Lantern', 'Stars', 'Rain', 'Song', 'Leaf'],
    ],
  },
  avian: {
    start: [
      'Aer',
      'Cae',
      'Dri',
      'Fe',
      'Kee',
      'Kri',
      'Pip',
      'Qui',
      'Sky',
      'Trill',
      'Vee',
      'Wy',
      'Zee',
      'Chir',
      'Hai',
    ],
    middle: ['', 'a', 'e', 'i', 'rr', 'ss'],
    end: [
      ['k', 'ka', 'rak', 'rik', 'tok', 'wing', 'yr'],
      ['ka', 'lia', 'ra', 'ree', 'sa', 'ti', 'wyn'],
    ],
    family: [
      'Featherfall',
      'High-Perch',
      'Quickwing',
      'Stormcrest',
      'Talonsworn',
      'Windrider',
      'Cloudmantle',
      'Bluecrest',
    ],
    familyChance: 0.6,
  },
  reptile: {
    start: ['Aks', 'Ess', 'Gar', 'Hiss', 'Ko', 'Os', 'Sar', 'Ssi', 'Tho', 'Vash', 'Xan', 'Za'],
    middle: ['', 'a', 'i', 'ss', 'u'],
    end: [
      ['ak', 'ath', 'esh', 'ik', 'ruk', 'ssus', 'tor'],
      ['a', 'ass', 'esa', 'ia', 'ith', 'sha', 'ssa'],
    ],
    family: ['Shell-Wise', 'of the Warm Stones', 'Slow-Tide', 'Reedwalker', 'Sunbasker'],
    familyChance: 0.4,
  },
  construct: {
    start: [
      'Ax',
      'Bolt',
      'Cog',
      'Dial',
      'Echo',
      'Flint',
      'Gauge',
      'Iron',
      'Lens',
      'Pike',
      'Rivet',
      'Spark',
      'Torque',
      'Vane',
    ],
    middle: ['', ''],
    end: [
      ['', '-7', '-12', ' Mark II', '-3', '-9'],
      ['', '-4', '-11', ' Mark III', '-6', '-8'],
    ],
    family: [
      'the Steadfast',
      'the Watchful',
      'Twelve',
      'the Tinkerer',
      'the Quiet',
      'Who Remembers',
    ],
    familyChance: 0.3,
  },
} satisfies Record<string, Style>;

export type NameStyle = keyof typeof STYLES;

/** The naming style of a species, by its name (any species of the character builder). */
export function styleFor(species: string): NameStyle {
  const s = species.toLowerCase();
  const has = (...words: string[]) => words.some((w) => s.includes(w));
  if (has('elf', 'drow', 'eladrin', 'shadar')) return 'elf';
  if (has('dwarf', 'duergar')) return 'dwarf';
  if (has('halfling')) return 'halfling';
  if (has('gnome', 'svirfneblin', 'autognome')) return has('autognome') ? 'construct' : 'gnome';
  if (has('orc')) return 'orc';
  if (has('tiefling')) return 'tiefling';
  if (has('dragonborn', 'dragon')) return 'dragonborn';
  if (has('goliath', 'firbolg', 'giant')) return 'giant';
  if (has('goblin', 'kobold', 'bugbear')) return 'goblin';
  if (has('aasimar')) return 'celestial';
  if (has('genasi', 'elemental')) return 'elemental';
  if (has('tabaxi', 'leonin', 'cat')) return 'feline';
  if (has('aven', 'aarakocra', 'kenku', 'owlin', 'bird')) return 'avian';
  if (has('tortle', 'lizard', 'yuan', 'triton', 'grung')) return 'reptile';
  if (has('warforged', 'construct', 'automaton')) return 'construct';
  return 'human';
}

/** A name in the style of a species; `gender` is woman, man or anything else. */
export function makeName(species: string, gender: string, rng: Rng = Math.random): string {
  const style: Style = STYLES[styleFor(species)];
  const ending =
    gender === 'woman' ? style.end[1] : gender === 'man' ? style.end[0] : pick(style.end, rng);
  const given = `${pick(style.start, rng)}${pick(style.middle, rng)}${pick(ending, rng)}`;
  if (!style.family || rng() > (style.familyChance ?? 1)) return given;
  const family = pick(style.family, rng);
  return style.join === ' "' ? `${given} "${family}"` : `${given}${style.join ?? ' '}${family}`;
}

/** Built-in species for when the builder's list is not loaded (no 5etools data yet). */
export const BASIC_SPECIES = [
  'Human',
  'Elf',
  'Dwarf',
  'Halfling',
  'Gnome',
  'Orc',
  'Tiefling',
  'Dragonborn',
  'Goliath',
  'Aasimar',
] as const;

/** `count` names, of one species or of any in `species` (each name says whose it is). */
export function generateNames(
  count: number,
  species: readonly string[],
  only?: string,
  rng: Rng = Math.random,
): { name: string; species: string }[] {
  const pool = species.length ? species : BASIC_SPECIES;
  return Array.from({ length: Math.max(1, Math.min(100, Math.round(count))) }, () => {
    const sp = only ?? pick(pool, rng);
    const gender = rng() < 0.5 ? 'woman' : 'man';
    return { name: makeName(sp, gender, rng), species: sp };
  });
}
