/**
 * The NPC generator's word lists: the app's own, so a generated NPC is the DM's to keep. Long
 * lists, so two NPCs rarely match; each line reads on its own after its label.
 */

export const GENDERS = ['woman', 'man', 'woman', 'man', 'person'] as const;

export const AGES = [
  'young',
  'barely grown',
  'young adult',
  'in their prime',
  'middle-aged',
  'greying',
  'old',
  'very old',
  'ancient for their kind',
];

export const OCCUPATIONS = [
  'innkeeper',
  'blacksmith',
  'merchant',
  'guard',
  'priest',
  'farmer',
  'scholar',
  'sailor',
  'thief',
  'noble',
  'hunter',
  'healer',
  'bard',
  'miner',
  'courier',
  'fortune teller',
  'stablehand',
  'tax collector',
  'alchemist',
  'retired adventurer',
  'cartographer',
  'dockhand',
  'barber-surgeon',
  'gambler',
  'herbalist',
  'jeweler',
  'locksmith',
  'mercenary',
  'moneylender',
  'ratcatcher',
  'scribe',
  'shipwright',
  'smuggler',
  'tailor',
  'tanner',
  'town crier',
  'undertaker',
  'watchmaker',
  'beekeeper',
  'brewer',
  'chandler',
  'cook',
  'fence',
  'gravedigger',
  'lamplighter',
  'mapseller',
  'pawnbroker',
  'puppeteer',
  'shepherd',
  'street preacher',
  'translator',
  'weaver',
  'woodcarver',
  'airship mechanic',
  'bounty hunter',
  'customs officer',
  'dancer',
  'falconer',
  'glassblower',
  'harbor pilot',
  'messenger',
  'perfumer',
  'rope maker',
  'sage',
  'spy',
  'toymaker',
];

export const BUILDS = [
  'tall and wiry',
  'short and stocky',
  'broad-shouldered',
  'thin as a rake',
  'heavyset',
  'muscular',
  'slight and quick',
  'lanky',
  'pot-bellied',
  'compact and strong',
  'willowy',
  'hunched',
  'barrel-chested',
  'gaunt',
  'soft and round',
  'athletic',
  'very small',
  'towering',
];

export const APPEARANCE = [
  'a scar across the chin',
  'ink-stained fingers',
  'missing two teeth',
  'a nervous twitch',
  'braided hair woven with beads',
  'a booming laugh',
  'a jeweled earring',
  'smells of smoke',
  'piercing pale eyes',
  'a limp and a cane',
  'freckles everywhere',
  'tattooed hands',
  'always eating something',
  'a burn mark on one cheek',
  'a glass eye',
  'a missing finger',
  'very long fingernails',
  'a crooked nose, broken more than once',
  'perfectly white teeth',
  'a shaved head with a painted sigil',
  'a birthmark shaped like a bird',
  'calloused hands',
  'one ear notched',
  'eyebrows that meet in the middle',
  'a gold tooth',
  'sun-cracked skin',
  'a raspy cough',
  'spectacles on a chain',
  'a prosthetic hand of brass',
  'mismatched eyes',
  'hair dyed a startling color',
  'a deep tan line where a ring used to be',
  'a silver nose ring',
  'ritual scars on the forearms',
  'a wooden leg',
  'a soot-black thumb',
  'very long braids',
  'a sharp widow’s peak',
  'a face full of piercings',
  'unblinking stare',
];

export const CLOTHING = [
  'patched leathers',
  'a fine coat a size too big',
  'travel-stained robes',
  'a sailor’s oilskin',
  'a guild apron full of tools',
  'mismatched armor pieces',
  'a faded military jacket',
  'silks gone threadbare',
  'a hooded cloak, always up',
  'spotless whites',
  'furs and bone charms',
  'a priest’s vestments with a stain',
  'a merchant’s velvet and rings',
  'a dockworker’s vest',
  'goggles pushed up on the forehead',
  'a borrowed noble’s outfit',
  'layers of scarves',
  'a uniform with the insignia torn off',
  'bright motley',
  'a dusty duster and wide hat',
  'barefoot, ankle bells',
  'a long coat full of pockets',
  'a black mourning dress or suit',
  'a gambler’s waistcoat',
  'work clothes caked in clay',
  'a scholar’s gown, ink-spotted',
];

export const PERSONALITY = [
  'friendly to a fault',
  'suspicious of strangers',
  'loud and boastful',
  'shy but curious',
  'grumpy until fed',
  'endlessly polite',
  'nervous and jumpy',
  'cheerfully rude',
  'quietly observant',
  'overly dramatic',
  'calm in any storm',
  'a terrible liar',
  'a compulsive flirt',
  'deeply superstitious',
  'easily bored',
  'fiercely loyal to friends',
  'always negotiating',
  'pessimistic but helpful',
  'a know-it-all',
  'gentle and patient',
  'quick to anger, quick to forgive',
  'obsessed with cleanliness',
  'a hopeless romantic',
  'cold and businesslike',
  'nosy about everyone',
  'stubborn as a mule',
  'brave to the point of folly',
  'nostalgic for better days',
  'secretly lonely',
  'paranoid about the authorities',
];

export const MANNERISMS = [
  'taps their fingers when thinking',
  'never looks anyone in the eye',
  'quotes old proverbs',
  'cleans their nails with a knife',
  'hums tunelessly',
  'counts coins while talking',
  'cracks their knuckles',
  'finishes others’ sentences',
  'laughs at their own jokes',
  'speaks of themselves in the third person',
  'whistles through their teeth',
  'sniffs everything handed to them',
  'touches a lucky charm',
  'paces while talking',
  'uses big words wrongly',
  'stares at the ceiling when lying',
  'makes animal noises when excited',
  'doodles on any surface',
  'gives everyone nicknames',
  'chews on a twig or pipe',
  'fidgets with a ring',
  'always sits facing the door',
  'speaks very slowly',
  'apologizes constantly',
  'winks too much',
];

export const VOICES = [
  'speaks in a whisper',
  'a deep, slow drawl',
  'fast and breathless',
  'thick regional accent',
  'sings half their words',
  'formal and stiff',
  'a squeaky voice',
  'gravelly, like stones',
  'lisps',
  'laughs between sentences',
  'pauses mid-sentence',
  'never finishes a thought',
  'a melodious, practiced voice',
  'clipped military commands',
  'a hoarse croak',
  'mumbles into their collar',
  'booming, as if on a stage',
  'a lilting, musical accent',
  'nasal and whiny',
  'warm and grandmotherly',
  'flat and expressionless',
  'stutters when nervous',
];

export const IDEALS = [
  'family above all',
  'coin is the only honest god',
  'the law must be kept',
  'freedom for everyone',
  'knowledge should be shared',
  'tradition keeps us alive',
  'the strong protect the weak',
  'every debt must be repaid',
  'beauty in all things',
  'power is the only safety',
  'change is always good',
  'charity, even when it hurts',
  'honor in all dealings',
  'survival, whatever it takes',
  'the gods are watching',
  'the old ways were better',
];

export const BONDS = [
  'a sibling in prison',
  'the shop their parent founded',
  'an old crewmate who saved them',
  'a child they never acknowledged',
  'their hometown, now in ruins',
  'a pet they adore',
  'a mentor who vanished',
  'a debt to a crime lord',
  'a temple that raised them',
  'a lover in another city',
  'a regiment that no longer exists',
  'a map they can’t read',
  'a promise made to a dying friend',
  'a rival they secretly admire',
  'the street kids they feed',
];

export const FLAWS = [
  'can’t resist a wager',
  'drinks too much',
  'trusts no one',
  'lies by reflex',
  'terrified of magic',
  'envies the rich',
  'never admits being wrong',
  'can’t keep a secret',
  'steals small things',
  'cowardly when it counts',
  'holds grudges forever',
  'falls for every flatterer',
  'judges by appearance',
  'greedy beyond reason',
  'reckless with others’ lives',
  'easily bribed',
];

export const WANTS = [
  'to pay off a debt',
  'revenge on an old rival',
  'to find a missing sibling',
  'fame and glory',
  'a quiet life',
  'to learn a forbidden secret',
  'to leave town for good',
  'a good drink and company',
  'to protect their family',
  'a rare ingredient',
  'to win back a lost love',
  'to prove themselves to a parent',
  'enough money to retire',
  'to see the sea',
  'a cure for an illness',
  'to get out of a contract',
  'a seat on the council',
  'their stolen heirloom back',
  'to be left alone',
  'news of a loved one at war',
  'to expose a corrupt official',
  'a partner for a risky scheme',
  'forgiveness',
  'to buy their own ship',
];

export const SECRETS = [
  'is a spy for a nearby lord',
  'owes money to dangerous people',
  'once was an adventurer',
  'saw something they should not have',
  'is not who they claim to be',
  'hides a stolen relic',
  'secretly worships a forbidden god',
  'is plotting to leave without paying',
  'knows a hidden path',
  'is related to the villain',
  'has a cursed item',
  'has no secret at all',
  'murdered someone long ago',
  'is a lycanthrope on full moons',
  'forges documents on the side',
  'is the masked vigilante everyone talks about',
  'sold out their old friends',
  'is a deserter',
  'can hear the dead',
  'is dying and tells no one',
  'runs an illegal fighting pit',
  'is in love with the party’s enemy',
  'is the rightful heir to a title',
  'hides a fugitive in the cellar',
];

export const KNOWS = [
  'which guard takes bribes',
  'a back way into the castle',
  'where the smugglers land',
  'that the mayor is being blackmailed',
  'an old map of the sewers',
  'the password to a secret club',
  'rumors of a dragon in the hills',
  'who really started the fire',
  'a cheap place to sleep',
  'which merchant sells fakes',
  'where a missing child was last seen',
  'the cult’s meeting day',
  'that the bridge is about to collapse',
  'a fence who asks no questions',
  'the local legends of a ruin',
  'nothing useful, but talks a lot',
  'a shortcut through the marsh',
  'when the next caravan leaves',
  'that a noble is hiring adventurers',
  'the true name of a ghost',
];

export const HOOKS = [
  'asks the party to deliver a sealed letter',
  'begs for help finding a lost pet',
  'wants a bodyguard for one night',
  'offers a job retrieving a family heirloom',
  'needs someone to settle a dispute',
  'is being followed and asks for cover',
  'sells a map to a "guaranteed" treasure',
  'wants a rival’s shop sabotaged',
  'needs an escort through dangerous country',
  'offers a reward for a wanted criminal',
  'asks for help with a haunting',
  'wants proof that their partner is cheating',
  'needs a rare monster part',
  'invites the party to a suspicious dinner',
  'wants to join the party',
  'is about to be arrested and pleads innocence',
  'has a dying wish',
  'offers free drinks for a story',
];

export const ATTITUDES = [
  'warm toward strangers',
  'wary of the party',
  'hostile to outsiders',
  'eager to please',
  'indifferent',
  'suspicious of the party’s motives',
  'impressed by the party’s reputation',
  'afraid of the party',
  'amused by the party',
];
